code --install-extension arcticicestudio.nord-visual-studio-code
code --install-extension bmalehorn.vscode-fish
code --install-extension EditorConfig.EditorConfig
code --install-extension hbenl.vscode-test-explorer
code --install-extension Lourenci.go-to-spec
code --install-extension matklad.rust-analyzer
code --install-extension mikestead.dotenv
code --install-extension ms-vscode.live-server
code --install-extension ms-vscode.test-adapter-converter
code --install-extension Orta.vscode-jest
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-russian
code --install-extension vadimcn.vscode-lldb
code --install-extension vscodevim.vim
code --install-extension VSpaceCode.whichkey
code --install-extension waderyan.gitblame