code --install-extension arcticicestudio.nord-visual-studio-code
code --install-extension bmalehorn.vscode-fish
code --install-extension darkriszty.markdown-table-prettify
code --install-extension EditorConfig.EditorConfig
code --install-extension GitHub.vscode-pull-request-github
code --install-extension hbenl.vscode-test-explorer
code --install-extension Lourenci.go-to-spec
code --install-extension mhutchie.git-graph
code --install-extension mikestead.dotenv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-vscode.hexeditor
code --install-extension ms-vscode.live-server
code --install-extension ms-vscode.test-adapter-converter
code --install-extension rust-lang.rust-analyzer
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-russian
code --install-extension Swellaby.vscode-rust-test-adapter
code --install-extension vadimcn.vscode-lldb
code --install-extension vscodevim.vim
code --install-extension VSpaceCode.whichkey
code --install-extension waderyan.gitblame
