export PATH=$HOME/bin:/usr/local/bin:$PATH
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"
HYPHEN_INSENSITIVE="true"

# ENABLE_CORRECTION="true"
# COMPLETION_WAITING_DOTS="true"
# DISABLE_MAGIC_FUNCTIONS=true
# DISABLE_UNTRACKED_FILES_DIRTY="true"
# export LANG=en_US.UTF-8
# export ARCHFLAGS="-arch x86_64"

plugins=(git)
source $ZSH/oh-my-zsh.sh

alias ttl4="sudo sysctl net.ipv4.ip_default_ttl=65"

if [ "$TMUX" = "" ]; then
	tmux attach -t base || tmux new -s base
fi

if [ -r ~/.dir_colors ]; then
	eval $(dircolors ~/.dir_colors)
fi
