format = """
[](fg:blue)\
$directory\
[](bg:yellow fg:blue)\
$git_branch\
$git_status\
[](fg:yellow bg:green)\
$nodejs\
$rust\
$elixir\
$python\
$conda\
$dart\
$elm\
$golang\
$java\
$julia\
$haskell\
$nim\
$lua\
[](fg:green bg:purple)\
$time\
[](fg:purple)
$character
"""

[character]
success_symbol = "[](blue)"
error_symbol = "[](red)"

[directory]
style = "bg:blue fg:black"
format = "[$path ]($style)"
truncation_length = 1
truncation_symbol = "ﱮ "

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:yellow fg:black"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:yellow fg:black"
stashed = ""
format = '[($all_status$ahead_behind )]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:purple fg:black"
format = '[ 神$time ]($style)'

[package]
disabled = true
symbol = ""

[aws]
disabled = true
symbol = ""

[conda]
symbol = ""
style = "bg:green fg:black"
format = '[[ $symbol ($version) ](bg:green fg:black)]($style)'

[dart]
symbol = ""
style = "bg:green fg:black"
format = '[[ $symbol ($version) ](bg:green fg:black)]($style)'

[elixir]
symbol = ""
style = "bg:green fg:black"
format = '[[ $symbol ($version) ](bg:green fg:black)]($style)'

[elm]
symbol = ""
style = "bg:green fg:black"
format = '[[ $symbol ($version) ](bg:green fg:black)]($style)'

[golang]
symbol = ""
style = "bg:green fg:black"
format = '[[ $symbol ($version) ](bg:green fg:black)]($style)'

[java]
symbol = ""
style = "bg:green fg:black"
format = '[[ $symbol ($version) ](bg:green fg:black)]($style)'

[julia]
symbol = ""
style = "bg:green fg:black"
format = '[[ $symbol ($version) ](bg:green fg:black)]($style)'

[nim]
symbol = ""
style = "bg:green fg:black"
format = '[[ $symbol ($version) ](bg:green fg:black)]($style)'

[nodejs]
symbol = ""
style = "bg:green fg:black"
format = '[[ $symbol ($version) ](bg:green fg:black)]($style)'

[python]
symbol = ""
style = "bg:green fg:black"
format = '[[ $symbol ($version) ](bg:green fg:black)]($style)'

[ruby]
symbol = ""
style = "bg:green fg:black"
format = '[[ $symbol ($version) ](bg:green fg:black)]($style)'

[rust]
symbol = ""
style = "bg:green fg:black"
format = '[[ $symbol ($version) ](bg:green fg:black)]($style)'

[haskell]
symbol = ""
style = "bg:green fg:black"
format = '[[ $symbol ($version) ](bg:green fg:black)]($style)'

[lua]
symbol = ""
style = "bg:green fg:black"
format = '[[ $symbol ($version) ](bg:green fg:black)]($style)'
